import type { BuilderNode, FlexSettings, GridSettings, LayoutMode } from "./types";
import { sortedNodes } from "./layout";

export class BuilderExporter {
  private escapeHtml(s: string) {
    return s
      .replaceAll("&", "&amp;")
      .replaceAll("<", "&lt;")
      .replaceAll(">", "&gt;");
  }

  private safeAttr(s: unknown) {
    if (s == null) return "";
    return String(s).replaceAll('"', "&quot;");
  }

  private nodeToHtml(n: BuilderNode): string {
    const t = n.type;
    const d = n.data ?? {};

    // First version: map only the common primitives you already have.
    // Fallback: emit a comment so it's obvious something exists.
    switch (t) {
      case "h1": {
        const text = d.text ?? d.value ?? "Heading";
        return `<h1>${this.escapeHtml(String(text))}</h1>`;
      }
      case "paragraph": {
        const text = d.text ?? d.value ?? "Text…";
        return `<p>${this.escapeHtml(String(text))}</p>`;
      }
      case "image": {
        const src = d.src ?? "";
        const alt = d.alt ?? "";
        return `<img src="${this.safeAttr(src)}" alt="${this.escapeHtml(
          String(alt),
        )}">`;
      }
      case "video": {
        const src = d.src ?? "";
        return `<video src="${this.safeAttr(src)}" controls></video>`;
      }
      case "audio": {
        const src = d.src ?? "";
        return `<audio src="${this.safeAttr(src)}" controls></audio>`;
      }
      case "divider": {
        return `<hr>`;
      }
      case "link": {
        const href = d.href ?? "#";
        const label = d.label ?? "Link";
        return `<a href="${this.safeAttr(
          href,
        )}" target="_blank" rel="noopener">${this.escapeHtml(
          String(label),
        )}</a>`;
      }
      case "button": {
        const label = d.label ?? "Button";
        return `<button type="button">${this.escapeHtml(
          String(label),
        )}</button>`;
      }
      case "icon": {
        const name = d.name ?? "gear";
        return `<span class="icon" data-icon="${this.safeAttr(name)}"></span>`;
      }
      default:
        return `<!-- unsupported: ${t} -->`;
    }
  }

  private indent(lines: string[], spaces = 2) {
    const pad = " ".repeat(spaces);
    return lines.map((l) => (l ? pad + l : l)).join("\n");
  }

  generateExport(args: {
    layoutMode: LayoutMode;
    nodes: BuilderNode[];
    flexSettings: FlexSettings;
    gridSettings: GridSettings;
  }): { html: string; css: string; combined: string } {
    const sorted = sortedNodes(args.nodes);

    const containerClass =
      args.layoutMode === "freeform"
        ? "page page--freeform"
        : args.layoutMode === "flex"
          ? "page page--flex"
          : args.layoutMode === "grid"
            ? "page page--grid"
            : "page page--flow";

    let bodyHtml = "";

    if (args.layoutMode === "freeform") {
      bodyHtml = sorted
        .map((n) => {
          const pos = n.pos ?? { x: 0, y: 0 };
          return `<div class="el" style="left:${Math.round(
            pos.x,
          )}px; top:${Math.round(pos.y)}px;">${this.nodeToHtml(n)}</div>`;
        })
        .join("\n");
    } else {
      bodyHtml = sorted
        .map((n) => {
          const display = n.display ?? "block";
          const cls = display === "inline" ? "el el--inline" : "el";
          return `<div class="${cls}">${this.nodeToHtml(n)}</div>`;
        })
        .join("\n");
    }

    const htmlLines = [
      `<!-- Generated by webwriter-website-builder -->`,
      `<div class="${containerClass}">`,
      this.indent(bodyHtml.split("\n"), 2),
      `</div>`,
    ];
    const htmlOut = htmlLines.join("\n");

    const flex = args.flexSettings;
    const grid = args.gridSettings;

    const cssOut = `/* Generated by webwriter-website-builder */
    .page {
      box-sizing: border-box;
      padding: 16px;
      background: #fff;
      color: #0f172a;
      font-family: system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
    }

    .page img, .page video {
      max-width: 100%;
      height: auto;
    }

    .page--freeform {
      position: relative;
      min-height: 600px;
    }

    .page--freeform .el {
      position: absolute;
    }

    .page--flow .el--inline {
      display: inline-block;
    }

    .page--flex {
      display: flex;
      flex-direction: ${flex.direction ?? "row"};
      justify-content: ${flex.justify ?? "flex-start"};
      align-items: ${flex.align ?? "stretch"};
      flex-wrap: ${flex.wrap ?? "nowrap"};
      gap: ${flex.gap ?? "12px"};
    }

    .page--grid {
      display: grid;
      grid-template-columns: ${grid.columns ?? "repeat(3, 1fr)"};
      grid-auto-rows: ${grid.rows ?? "auto"};
      gap: ${grid.gap ?? "12px"};
    }

    /* Icons: placeholder representation */
    .page .icon::before {
      content: attr(data-icon);
      font-size: 12px;
      opacity: 0.7;
      border: 1px solid #e5e7eb;
      padding: 2px 6px;
      border-radius: 999px;
    }
    `;

    const combined = `<!-- HTML -->
    ${htmlOut}

    <style>
    ${cssOut}
    </style>`;

    return { html: htmlOut, css: cssOut, combined };
  }
}
